### ISSUE TITLE
tutorials/versioning/data.zip

### ISSUE THREAD

**Issue by zakraicik** [iterative/dataset-registry#15]
Trying to run 

`dvc get https://github.com/iterative/dataset-registry   \
          tutorials/versioning/data.zip`

However, I get this error. 

`ERROR: unexpected error - : Unable to find DVC file with output '../../../../private/var/folders/pq/57gd7mhx08g_66qwkzjmf6xh0000gn/T/tmp6n27kbdldvc-clone/tutorials/versioning/data.zip'
`

Am I doing something wrong?

**Comment by shcheklein** [comment]
@jorgeorpinel I think this commit https://github.com/iterative/dataset-registry/commit/9f3e3026ab6fc1d19e13f94c6c52792bac17ed64 broke this .. could you please take a look?

**Comment by jorgeorpinel** [comment]
@zakraicik for now please use 

`dvc get https://github.com/iterative/dataset-registry tutorials/ver/data.zip`

while I address the root cause. Thanks

**Comment by jorgeorpinel** [comment]
OK, should be fixed! `dvc get https://github.com/iterative/dataset-registry tutorials/versioning/data.zip` works for me. BTE please remove that `\` if pasting the command in a single line @zakraicik
