### ISSUE TITLE
tutorial -> tutorials

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dataset-registry#3]
To match https://github.com/iterative/dvc.org/pull/666

And maybe rename the `ver` subdirectories to `versioning`.

This will involve changes in dvc.org docs (search for `tutorial/`).

**Comment by iesahin** [comment]
I'd propose a more independent directory structure that's not directly tied to the docs. `tutorials/ver/` can be `cats-and-dogs/`. 

I don't know much about `tutorials/nlp/`, it looks no current doc uses it. A similar path is found in old blog posts [here](https://github.com/iterative/dvc.org/blob/29e5d55bc0965b9919abcc3f747e3f76a010239c/content/blog/2017-07-24-r-code-and-reproducible-model-development-with-dvc.md#L127) and [here](https://github.com/iterative/dvc.org/blob/29e5d55bc0965b9919abcc3f747e3f76a010239c/content/blog/2017-09-26-best-practices-of-orchestrating-python-and-r-code-in-ml-projects.md#L156), but it doesn't use the registry. 

I think renaming these independently will reduce the need for renames in later doc reorganizations, and possibly increase the reuse.

@jorgeorpinel @shcheklein

**Comment by iesahin** [comment]
`tutorial/ver` is referenced in two places in the docs. One is the [ref for `dvc import`](https://github.com/iterative/dvc.org/blob/29e5d55bc0965b9919abcc3f747e3f76a010239c/content/docs/command-reference/import.md#L213) and the other is [the tutorial itself](https://github.com/iterative/dvc.org/blob/359f3be0454c8b6678e2a47808959355758630ed/content/docs/use-cases/versioning-data-and-model-files/tutorial.md#L193).

**Comment by jorgeorpinel** [comment]
> a more independent directory structure that's not directly tied to the docs. tutorials/ver/ can be cats-and-dogs/.
reduce the need for renames in later doc reorganizations

Good idea! But if you look in [tutoral/ver/](https://github.com/iterative/dataset-registry/tree/master/tutorial) it's structured specifically for a versioning tutorial (not a tutorial about labeling cats and dogs) so the name looks accurate to me. It's also already independent: the path in the docs site is use-cases/versioning-data-and-model-files/tutorial

**Comment by jorgeorpinel** [comment]
@iesahin mind reviewing iterative/dvc.org/pull/2451 (needs an approval)? We can continue the discussion there if needed. Thanks!
