### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dataset-registry#30]
The readme states:

> This is an auto-generated repository for use in https://dvc.org/doc/. Please report any issues in its source project, [example-repos-dev](https://github.com/iterative/example-repos-dev).

I don't see a corresponding project in example-repos-dev to generate this repo. Are these instructions outdated?

**Comment by jorgeorpinel** [comment]
Yeah strange. Maybe just delete the README.md file for now? Or just put a link to https://dvc.org/doc/use-cases/data-registry which I believe is the only doc that uses it.

**Comment by jorgeorpinel** [comment]
Jk it's also used in

- https://dvc.org/doc/start/data-management/data-and-model-access
- https://dvc.org/doc/command-reference/import
- https://dvc.org/doc/api-reference/get_url

**Comment by jorgeorpinel** [comment]
Oops meant to open a PR but my edit was [committed](https://github.com/iterative/dataset-registry/commit/c172a9b59c7f30a5f83a87adb9296406676dfffa) directly. PTAL @dberenbaum @shcheklein

**Comment by dberenbaum** [comment]
LGTM @jorgeorpinel!
