### ISSUE TITLE
How to obtain the "data.xml" file

### ISSUE THREAD

**Issue by liyan1997** [iterative/dataset-registry#38]
I did not find the data.xml file in the get-started path

**Comment by efiop** [comment]
@liyan1997 Are you following some tutorial or something?

**Comment by liyan1997** [comment]
@efiop Yes, I followed a tutorial, but when I executed 'dvc get https://github.com/iterative/dataset-registry \
>getting-started/data.xml - o data/data.xml ", the prompt" error: the following arguments are required: path "appears to be a parameter error, but I don't know how to solve it. Thank you for your reply

**Comment by efiop** [comment]
@liyan1997 You are probably copypasting it wrong with the \ and also the `path` is wrong (it is get-started, not getting-started). Try:

```
dvc get https://github.com/iterative/dataset-registry get-started/data.xml
```

Also which tutorial? Could you show us a link so we could check if it needs adjustment?

**Comment by liyan1997** [comment]
@efiop Sorry, this is my spelling error. In fact, I used 'get started', but I seem to have solved the problem because I abandoned the '- o' command and used the command you provided. The connection I referenced is as follows: https://juejin.cn/post/7057767026072223751 This is a Chinese website. I wonder if you can access it. Thank you again for your reply

**Comment by efiop** [comment]
Great to hear it works now. Closing.
