### ISSUE TITLE
Failed to clone repo

### ISSUE THREAD

**Issue by Damon-Salvatore-liu** [iterative/dataset-registry#42]
When I use the following command
"dvc get https://github.com/iterative/dataset-registry \
get-started/data.xml -o data/data.xml" 
prompt
"ERROR: failed to get 'get-started/data.xml' - SCM error: Failed to clone repo 'https://github.com/iterative/dataset-registry' to '/var/folders/5t/8_l102dd23z_gj9r3j41sy140000gn/T/tmp850oahzxdvc-clone': name 'urllib3' is not defined"

**Comment by shcheklein** [comment]
Please run the command with `-v`.
` name 'urllib3' is not defined"` is a minor bug in requests AFAIU, it happens when it handles some connection exception, e.g. SSL - the actual cause should be visible in logs.

**Comment by elifbuyukorhan** [comment]
I use same command :
"dvc get https://github.com/iterative/dataset-registry
get-started/data.xml -o data/data.xml"

I got this:
'../../../../tmp/tmph_ii91gydvc-clone/dvc.yaml' validation failed.                                                                          

extra keys not allowed, in artifacts, line 2, column 3
  1 artifacts:                                                                                                                              
  2   get-started-data:

**Comment by dberenbaum** [comment]
@elifbuyukorhan Could you please update your DVC version and try again?
