### ISSUE TITLE
DVC get from get started DOCS not working after last commit

### ISSUE THREAD

**Issue by phbonamin** [iterative/dataset-registry#47]
I was running a demo this morning( 29/04 UTC 00:51 PM )
and the command:
``dvc get https://github.com/iterative/dataset-registry  get-started/data.xml -o data/data.xml `` was working perfectly fine.

I get this command from following the docs:

https://dvc.org/doc/start

After the commit cdc0b6b i get the following error, which i could not solve for :

``ERROR: unexpected error - [Errno 2] No storage files available: 'get-started/data.xml``

I currently running dvc with the following configs:
``````
DVC version: 3.50.1 (pip)

Platform: Python 3.10.12 on Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 3.15.1
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.4.0
        scmrepo = 3.3.2
Supports:
        gs (gcsfs = 2024.3.1),
        http (aiohttp = 3.9.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.5, aiohttp-retry = 2.8.3)
``````
What is the issue? Is the dataset not available after last commit?

**Comment by dberenbaum** [comment]
Should be working now. Sorry for the inconvenience!

**Comment by phbonamin** [comment]
Solved! Thanks for the reply
