### ISSUE TITLE
Failed SSL certificate on tutorial dvc get

### ISSUE THREAD

**Issue by SylviaWhittle** [iterative/dataset-registry#48]
Hi 😄 

(Apologies if this is a stupid user-error or the wrong place to post - do tell me if so)

I am a new user and trying to do the [tutorial exercise](https://dvc.org/doc/use-cases/versioning-data-and-models/tutorial).

When running the command `dvc get https://github.com/iterative/dataset-registry tutorials/versioning/data.zip`, I get the following error:

```zsh
❯ dvc --version
3.50.0
❯ dvc get https://github.com/iterative/dataset-registry tutorials/versioning/data.zip
ERROR: failed to get 'tutorials/versioning/data.zip' - SCM error: Failed to clone repo 'https://github.com/iterative/dataset-registry' to '/var/folders/sr/wjtfqr9s6x3bw1s647t649x80000gn/T/tmp9dut6q7idvc-clone': HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /iterative/dataset-registry/info/refs?service=git-upload-pack (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))): HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /iterative/dataset-registry/info/refs?service=git-upload-pack (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

I know nothing about certificates, and tried utilising LLMs to guide my troubleshooting.

I found [one post](https://stackoverflow.com/questions/74422406/dvc-push-certificate-verify-fail-for-gcp) talking about certificates, but I don't seem to have access to the certificate update command they reference. Though I do have an up to date `certifi` module in my virtual environment which the LLM says should be good enough to ensure up-to-date certificates. (Sorry I know little about them).

[Technical details]
Device: MacBook Pro 14" (2021)
OS: MacOS Version 14.4.1 (23E224) (Up-to-date)
Processor: M1 Pro (2021)(ARM)
Shell: zsh
Python: virtualenv environment 3.9 & conda environment 3.11
DVC: 3.50.0

[Steps attempted]
- Update Operating System
- Update pip
- Try conda
- Try virtualenv
- Create a fresh directory
- Use sudo
- Restart my computer
- Use a different network (Wifi & wired)
- Check system date and time are accurate.
- Attempt to update dvc (already updated)
- Attempt to update certificates
- Try the other `dvc get` command from another tutorial: `dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data/data.xml`
- Ran the command (successfully) on Linux (python 3.10) (x86) - hence it's an issue with my MacBook.

I know this is likely an issue with my computer, but I am posting just in case as I am out of ideas aside from a full OS-reinstall (which I will do if needed).

I searched online about this and came across a couple posts, however they don't seem to have certificate issues. Issue #42 might be relevant?

Thank you for your time 🙏

**Comment by dberenbaum** [comment]
Are you able to clone that repo like `git clone https://github.com/iterative/dataset-registry`?

**Comment by SylviaWhittle** [comment]
Thanks for your reply 😄 

Yes, cloning the repo via that command succeeds:

```zsh
❯ git clone https://github.com/iterative/dataset-registry
Cloning into 'dataset-registry'...
remote: Enumerating objects: 322, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 322 (delta 52), reused 56 (delta 37), pack-reused 205
Receiving objects: 100% (322/322), 48.97 KiB | 2.72 MiB/s, done.
Resolving deltas: 100% (84/84), done.
```

I was very confused at how this succeeds but the `dvc get` command doesn't

**Comment by dberenbaum** [comment]
If you are just looking to get unblocked for the tutorial, you can point to that local repo instead like `dvc get /path/to/dataset-registry tutorials/versioning/data.zip`.
